[package]
name = "godotnearest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
kdtree = "0"
regex-automata = { version = "0", features = ["meta"] }
